simc.exe Arcane_FAE.simc
simc.exe Arcane_KYR.simc
simc.exe arcane_legendaries.simc
simc.exe Arcane_NEC.simc
simc.exe Arcane_VEN.simc
simc.exe Fire_FAE.simc
simc.exe Fire_KYR.simc
simc.exe fire_legendaries.simc
simc.exe Fire_NEC.simc
simc.exe Fire_VEN.simc
simc.exe Frost_FAE.simc
simc.exe Frost_KYR.simc
simc.exe frost_legendaries.simc
simc.exe Frost_NEC.simc
simc.exe Frost_VEN.simc
